#! /bin/sh
set -e
echo "DEBUG: post-receive invoked"
echo "ref $ref received.  Starting batch-job..."
worktree_base=$(realpath ..)
branch=$(date +%FT%H%M%S)
worktree=$worktree_base/$branch
git worktree add $worktree
cd $worktree

echo "todo... run snakemake"

echo "when the job is done, fetch results with: git pull batch" $branch
cd -
